name: Pipeline Básico

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Listar arquivos
        run: ls -la

      - name: Mensagem
        run: echo "Pipeline rodando com sucesso!"
